oe_paragraphs:
  install:
    core.entity_form_display.paragraph.oe_accordion.default: ~
    core.entity_form_display.paragraph.oe_accordion_item.default: ~
    core.entity_form_display.paragraph.oe_content_row.default: ~
    core.entity_form_display.paragraph.oe_links_block.default: ~
    core.entity_form_display.paragraph.oe_list_item.default: ~
    core.entity_form_display.paragraph.oe_list_item_block.default: ~
    core.entity_form_display.paragraph.oe_quote.default: ~
    core.entity_form_display.paragraph.oe_rich_text.default: ~
    core.entity_view_display.paragraph.oe_accordion.default: ~
    core.entity_view_display.paragraph.oe_accordion_item.default: ~
    core.entity_view_display.paragraph.oe_content_row.default: ~
    core.entity_view_display.paragraph.oe_links_block.default: ~
    core.entity_view_display.paragraph.oe_list_item.default: ~
    core.entity_view_display.paragraph.oe_list_item_block.default: ~
    core.entity_view_display.paragraph.oe_quote.default: ~
    core.entity_view_display.paragraph.oe_rich_text.default: ~
    field.field.paragraph.oe_accordion.field_oe_paragraphs: ~
    field.field.paragraph.oe_accordion_item.field_oe_icon: ~
    field.field.paragraph.oe_accordion_item.field_oe_text: ~
    field.field.paragraph.oe_accordion_item.field_oe_text_long: ~
    field.field.paragraph.oe_content_row.field_oe_content_row_variant: ~
    field.field.paragraph.oe_content_row.field_oe_paragraphs: ~
    field.field.paragraph.oe_content_row.field_oe_title: ~
    field.field.paragraph.oe_links_block.field_oe_links: ~
    field.field.paragraph.oe_links_block.field_oe_text: ~
    field.field.paragraph.oe_list_item.field_oe_date: ~
    field.field.paragraph.oe_list_item.field_oe_image: ~
    field.field.paragraph.oe_list_item.field_oe_link: ~
    field.field.paragraph.oe_list_item.field_oe_list_item_variant: ~
    field.field.paragraph.oe_list_item.field_oe_meta: ~
    field.field.paragraph.oe_list_item.field_oe_text_long: ~
    field.field.paragraph.oe_list_item.field_oe_title: ~
    field.field.paragraph.oe_list_item_block.field_oe_link: ~
    field.field.paragraph.oe_list_item_block.field_oe_list_item_block_variant: ~
    field.field.paragraph.oe_list_item_block.field_oe_paragraphs: ~
    field.field.paragraph.oe_list_item_block.field_oe_title: ~
    field.field.paragraph.oe_quote.field_oe_plain_text_long: ~
    field.field.paragraph.oe_quote.field_oe_text: ~
    field.field.paragraph.oe_rich_text.field_oe_text_long: ~
    field.field.paragraph.oe_rich_text.field_oe_title: ~
    field.storage.paragraph.field_oe_content_row_variant: ~
    field.storage.paragraph.field_oe_date: ~
    field.storage.paragraph.field_oe_icon: ~
    field.storage.paragraph.field_oe_image: ~
    field.storage.paragraph.field_oe_link: ~
    field.storage.paragraph.field_oe_links: ~
    field.storage.paragraph.field_oe_list_item_block_variant: ~
    field.storage.paragraph.field_oe_list_item_variant: ~
    field.storage.paragraph.field_oe_meta: ~
    field.storage.paragraph.field_oe_paragraphs: ~
    field.storage.paragraph.field_oe_plain_text_long: ~
    field.storage.paragraph.field_oe_text: ~
    field.storage.paragraph.field_oe_text_long: ~
    field.storage.paragraph.field_oe_title: ~
    paragraphs.paragraphs_type.oe_accordion: ~
    paragraphs.paragraphs_type.oe_accordion_item: ~
    paragraphs.paragraphs_type.oe_content_row: ~
    paragraphs.paragraphs_type.oe_links_block: ~
    paragraphs.paragraphs_type.oe_list_item: ~
    paragraphs.paragraphs_type.oe_list_item_block: ~
    paragraphs.paragraphs_type.oe_quote: ~
    paragraphs.paragraphs_type.oe_rich_text: ~
  optional:
    language.content_settings.paragraph.oe_accordion: ~
    language.content_settings.paragraph.oe_accordion_item: ~
    language.content_settings.paragraph.oe_content_row: ~
    language.content_settings.paragraph.oe_links_block: ~
    language.content_settings.paragraph.oe_list_item: ~
    language.content_settings.paragraph.oe_list_item_block: ~
    language.content_settings.paragraph.oe_quote: ~
    language.content_settings.paragraph.oe_rich_text: ~
